/**
 * @file Glossary: one definition per term, shown as hover pop-ups for
 *       <span class="term" data-g="key">…</span> and listed in the appendix.
 * Definitions may contain TeX between $…$ (rendered with KaTeX).
 */

/** @type {Record<string, {term: string, def: string}>} */
export const GLOSSARY = {
  pde: { term: 'PDE', def: 'Partial differential equation: an equation relating an unknown function of several variables (e.g. $u(x,y,t)$) to its partial derivatives.' },
  domain: { term: 'Domain $\\Omega$', def: 'The region of space where the PDE is posed (an open set in $\\mathbb{R}^d$). Its boundary is $\\partial\\Omega$.' },
  normal: { term: 'Outward unit normal $\\mathbf{n}$', def: 'At a boundary point, the unit vector perpendicular to the boundary pointing out of the region (like a face normal of a closed mesh).' },
  gradient: { term: 'Gradient $\\nabla u$', def: 'The vector of partial derivatives $(\\partial u/\\partial x, \\partial u/\\partial y)$; points in the direction of steepest increase of $u$.' },
  divergence: { term: 'Divergence $\\nabla\\cdot\\mathbf{F}$', def: '$\\partial F_x/\\partial x + \\partial F_y/\\partial y$: the net outflow of the vector field $\\mathbf{F}$ per unit area at a point (sources > 0, sinks < 0).' },
  laplacian: { term: 'Laplacian $\\Delta u$', def: '$\\nabla\\cdot\\nabla u = u_{xx} + u_{yy}$. Measures how much $u$ differs from its local average (used in mesh smoothing!).' },
  divthm: { term: 'Divergence theorem', def: '$\\int_\\Omega \\nabla\\cdot\\mathbf{F}\\,dx = \\int_{\\partial\\Omega}\\mathbf{F}\\cdot\\mathbf{n}\\,ds$: total source inside equals total flux through the boundary.' },
  flux: { term: 'Flux', def: 'A vector field $\\mathbf{F}$ describing the rate at which a quantity (mass, heat, momentum) crosses a unit length (2D) or area (3D) per unit time. The flux through a curve with normal $\\mathbf{n}$ is $\\int \\mathbf{F}\\cdot\\mathbf{n}\\,ds$.' },
  numflux: { term: 'Numerical flux $\\hat F$', def: 'A function $\\hat F(u^-,u^+,\\mathbf{n})$ that approximates the physical normal flux on a cell face from the two (possibly different) values on either side. It must be consistent: $\\hat F(u,u,\\mathbf{n}) = \\mathbf{F}(u)\\cdot\\mathbf{n}$.' },
  conslaw: { term: 'Conservation law', def: 'A PDE of the form $\\partial_t u + \\nabla\\cdot\\mathbf{F}(u) = 0$: the amount of $u$ in any region changes only by flux through its boundary.' },
  characteristic: { term: 'Characteristic', def: 'A curve in space–time along which information (the solution value, for scalar laws) travels. For $u_t + a u_x = 0$ these are the lines $x - at = $ const.' },
  shock: { term: 'Shock', def: 'A moving discontinuity in the solution of a nonlinear conservation law, formed when characteristics cross.' },
  rh: { term: 'Rankine–Hugoniot condition', def: 'The speed $s$ of a discontinuity satisfies $s\\,[u] = [F(u)]$ (jump of flux = speed × jump of state). It follows from the integral form of the conservation law.' },
  riemann: { term: 'Riemann problem', def: 'A conservation law with piecewise-constant initial data with a single jump. Its exact solution is the building block of Godunov-type numerical fluxes.' },
  cfl: { term: 'CFL condition', def: 'Courant–Friedrichs–Lewy: an explicit scheme is stable only if the time step is small enough that information does not travel further than (a fraction of) a cell per step: $\\Delta t \\le C\\, h/|a|$.' },
  weakform: { term: 'Weak form', def: 'The PDE multiplied by a test function $v$ and integrated over $\\Omega$, with derivatives moved onto $v$ by integration by parts. Requires less smoothness of $u$.' },
  testfn: { term: 'Test function', def: 'A function $v$ used to "probe" the equation: instead of requiring the PDE at every point, we require $\\int (\\text{residual})\\,v = 0$ for all $v$ in a test space.' },
  galerkin: { term: 'Galerkin method', def: 'Choose a finite-dimensional space $V_h$ and require the weak form for all test functions $v_h\\in V_h$, with the solution $u_h\\in V_h$ (same space for trial and test).' },
  essential: { term: 'Essential BC', def: 'A boundary condition built into the function space (e.g. Dirichlet $u = g$ in the standard weak form). Must be imposed explicitly ("strongly").' },
  natural: { term: 'Natural BC', def: 'A boundary condition that appears automatically in the boundary term of the weak form (e.g. Neumann $\\nabla u\\cdot\\mathbf{n} = g_N$ for Poisson).' },
  dirichlet: { term: 'Dirichlet condition', def: 'Prescribes the value of the solution on the boundary: $u = g$ on $\\Gamma_D$.' },
  neumann: { term: 'Neumann condition', def: 'Prescribes the normal derivative (the flux) on the boundary: $\\nabla u\\cdot\\mathbf{n} = g_N$ on $\\Gamma_N$.' },
  l2: { term: '$L^2$ norm', def: '$\\|v\\|_{L^2(\\Omega)} = (\\int_\\Omega v^2\\,dx)^{1/2}$ — the root-mean-square size of a function (times $\\sqrt{|\\Omega|}$).' },
  h1: { term: '$H^1$ (semi)norm', def: '$|v|_{H^1} = \\|\\nabla v\\|_{L^2}$ measures the size of the gradient; $H^1(\\Omega)$ is the space of functions with square-integrable gradients.' },
  order: { term: 'Order of convergence', def: 'A method converges with order $r$ if the error behaves like $C h^r$ as the mesh size $h\\to 0$; halving $h$ divides the error by $2^r$.' },
  mesh: { term: 'Mesh $\\mathcal{T}_h$', def: 'A partition of the domain into elements (cells) $K$ — triangles, quads, …; $h$ denotes the (maximum) element diameter.' },
  element: { term: 'Element $K$', def: 'One cell of the mesh. Each element is the image of a fixed reference element $\\hat K$ under a (usually affine) map.' },
  refelem: { term: 'Reference element $\\hat K$', def: 'A fixed "model" cell, e.g. $[-1,1]$ or the triangle with vertices (0,0),(1,0),(0,1). All computations are done there and mapped, like texture space vs world space.' },
  jacobian: { term: 'Jacobian $J$', def: 'The derivative matrix of the map from the reference element to the physical element; $|\\det J|$ scales areas, $J^{-T}$ maps reference gradients to physical gradients.' },
  basisfn: { term: 'Basis function', def: 'One of the functions $\\varphi_j$ spanning the discrete space; the discrete solution is $u_h = \\sum_j U_j \\varphi_j$ with unknown coefficients (degrees of freedom) $U_j$.' },
  dof: { term: 'Degree of freedom (DOF)', def: 'One unknown coefficient of the discrete solution. The number of DOFs is the size of the linear system.' },
  stiffness: { term: 'Stiffness matrix $A$', def: '$A_{ij} = \\int_\\Omega \\nabla\\varphi_j\\cdot\\nabla\\varphi_i\\,dx$ for the Poisson problem. Symmetric, positive definite (after boundary conditions), sparse.' },
  massmat: { term: 'Mass matrix $M$', def: '$M_{ij} = \\int \\varphi_j\\varphi_i\\,dx$, the Gram matrix of the basis in $L^2$.' },
  assembly: { term: 'Assembly', def: 'Building the global matrix by looping over elements, computing small local matrices and adding them at the global DOF indices (scatter-add).' },
  spd: { term: 'SPD', def: 'Symmetric positive definite: $A = A^T$ and $x^T A x > 0$ for all $x\\neq 0$. Such systems are solved by Cholesky or the conjugate-gradient method.' },
  condition: { term: 'Condition number $\\kappa(A)$', def: '$\\kappa = \\lambda_{\\max}/\\lambda_{\\min}$ for SPD $A$: the factor by which relative errors can be amplified in a solve; also controls iterative-solver speed.' },
  cgsolver: { term: 'Conjugate gradient (CG)', def: 'An iterative solver for SPD systems that only needs matrix–vector products; converges in roughly $\\sqrt{\\kappa}$ iterations.' },
  nitsche: { term: 'Nitsche’s method', def: 'Weak imposition of Dirichlet conditions by adding consistent boundary terms plus a penalty $\\frac{\\gamma}{h}\\int (u-g)v$. Keeps the method consistent (exact solution satisfies it) and stable for $\\gamma$ large enough.' },
  penalty: { term: 'Penalty method', def: 'Imposes a constraint approximately by adding a large multiple of its violation, e.g. $\\frac{\\gamma}{h}\\int (u-g)v$. Without the extra Nitsche terms it is inconsistent.' },
  cellavg: { term: 'Cell average $\\bar u_K$', def: '$\\frac{1}{|K|}\\int_K u\\,dx$, the unknown of a finite-volume method.' },
  upwind: { term: 'Upwind', def: 'Taking information from the direction the flow comes from. The upwind flux uses the state on the side the characteristic comes from.' },
  limiter: { term: 'Limiter', def: 'A nonlinear device that reduces the slope (or high-order content) of a reconstruction near discontinuities to prevent spurious oscillations.' },
  tvd: { term: 'TVD', def: 'Total variation diminishing: $\\sum_i |u_{i+1}-u_i|$ does not increase in time — no new wiggles.' },
  broken: { term: 'Broken space', def: 'A space of functions that are polynomials on each element with no continuity required across element faces (the DG space $V_h^p$).' },
  jump: { term: 'Jump $[\\![u]\\!]$', def: 'On a face between $K^-$ and $K^+$: $[\\![u]\\!] = u^- - u^+$ (scalar convention). For the vector form: $u^-\\mathbf{n}^- + u^+\\mathbf{n}^+$.' },
  average: { term: 'Average $\\{\\!\\{u\\}\\!\\}$', def: '$\\frac12(u^- + u^+)$ on an interior face.' },
  modal: { term: 'Modal basis', def: 'A basis of hierarchical "shapes" (e.g. Legendre polynomials); coefficients are like Fourier coefficients.' },
  nodal: { term: 'Nodal basis', def: 'A Lagrange basis attached to points (nodes); coefficients are the function values at the nodes.' },
  gll: { term: 'GLL nodes', def: 'Gauss–Lobatto–Legendre points: the endpoints ±1 and the roots of $P_p\'$. Good interpolation nodes and a quadrature rule exact up to degree $2p-1$.' },
  ssprk: { term: 'SSP Runge–Kutta', def: 'Strong-stability-preserving RK: a convex combination of forward-Euler steps, so properties like TVD are inherited under a CFL restriction.' },
  spectrum: { term: 'Spectrum', def: 'The set of eigenvalues of the semi-discrete operator. An explicit time integrator is stable when all $\\lambda\\,\\Delta t$ lie in its stability region.' },
  fr: { term: 'Flux reconstruction (FR)', def: 'A high-order method (Huynh 2007) that builds a continuous flux polynomial per element by adding correction functions to the discontinuous flux, then differentiates it at solution points.' },
  correction: { term: 'Correction function $g$', def: 'A polynomial of degree $p+1$ with $g_L(-1)=1, g_L(1)=0$ used in FR to correct the flux at the left interface (and its mirror $g_R$).' },
  sipg: { term: 'SIPG', def: 'Symmetric interior penalty Galerkin: DG for diffusion obtained by applying Nitsche’s method on every interior face.' },
  saddle: { term: 'Saddle-point problem', def: 'A linear system of block form $\\begin{pmatrix}A & B^T\\\\ B & 0\\end{pmatrix}$ arising from constraints; it is symmetric but indefinite.' },
  infsup: { term: 'Inf–sup condition', def: 'The compatibility condition between the two spaces of a mixed method (LBB condition) that guarantees a stable saddle-point problem.' },
  rt: { term: 'Raviart–Thomas space', def: '$H(\\mathrm{div})$-conforming vector elements: the normal component is continuous across faces, so fluxes are conserved exactly.' },
  hybrid: { term: 'Hybridization', def: 'Relaxing inter-element continuity and re-imposing it with Lagrange multipliers living only on the mesh skeleton (faces); element unknowns can then be eliminated locally.' },
  condensation: { term: 'Static condensation', def: 'Eliminating element-interior unknowns element-by-element (a Schur complement), leaving a smaller global system on the skeleton.' },
  schur: { term: 'Schur complement', def: 'For a block system $\\begin{pmatrix}A&B\\\\C&D\\end{pmatrix}$, eliminating the first block gives $S = D - C A^{-1} B$.' },
  skeleton: { term: 'Mesh skeleton $\\mathcal{E}_h$', def: 'The set of all faces (edges in 2D) of the mesh.' },
  hdg: { term: 'HDG', def: 'Hybridizable discontinuous Galerkin: DG whose numerical trace is a new unknown $\\hat u$ on the skeleton, so the global system only involves face unknowns.' },
  ddm: { term: 'Domain decomposition', def: 'Splitting a problem into subproblems on subdomains, solved independently (in parallel) and coupled through interface conditions or iterations.' },
  schwarz: { term: 'Schwarz method', def: 'Domain decomposition with overlapping subdomains: alternately (or simultaneously) solve on each subdomain using the latest values from the neighbours as boundary data.' },
  coarse: { term: 'Coarse space', def: 'A small global problem added to a domain decomposition preconditioner to propagate information across all subdomains at once; needed for scalability.' },
  levelset: { term: 'Level set $\\phi$', def: 'An implicit description of a domain: $\\Omega = \\{\\phi<0\\}$, boundary $\\Gamma = \\{\\phi = 0\\}$. A signed distance function (SDF) is a special level set.' },
  cutcell: { term: 'Cut cell', def: 'A background-mesh cell intersected by the boundary $\\Gamma$; only part of it lies in the physical domain.' },
  smallcut: { term: 'Small-cut problem', def: 'When a cut cell has only a tiny part inside the domain, the discrete system becomes arbitrarily ill-conditioned (and explicit time steps tiny) unless stabilised.' },
  ghostpenalty: { term: 'Ghost penalty', def: 'CutFEM stabilisation: penalise jumps of normal derivatives across faces of cut elements, which extends control from the physical part to the whole active elements.' },
  cutfem: { term: 'CutFEM', def: 'Unfitted finite elements: the background mesh ignores the boundary; integrals are restricted to the physical domain, boundary conditions imposed by Nitsche, stability ensured by ghost penalty.' },
  webspline: { term: 'WEB-splines', def: 'Weighted extended B-splines (Höllig): B-splines multiplied by a weight function that vanishes on the boundary; unstable outer B-splines are absorbed into inner ones by extrapolation.' },
  sbm: { term: 'Shifted Boundary Method', def: 'Main & Scovazzi: solve on the surrogate domain of uncut cells and impose the boundary condition there, shifted by a Taylor expansion along the distance vector to the true boundary.' },
  surrogate: { term: 'Surrogate boundary $\\tilde\\Gamma$', def: 'The boundary of the union of mesh cells lying completely inside the domain; it approximates the true boundary within one cell size.' },
  simt: { term: 'SIMT', def: 'Single instruction, multiple threads: GPU execution model where groups of threads (warps / wavefronts / subgroups) execute the same instruction on different data.' },
  coalescing: { term: 'Memory coalescing', def: 'When neighbouring GPU threads access neighbouring memory addresses, the hardware merges the accesses into few wide transactions.' },
  workgroup: { term: 'Workgroup', def: 'A group of GPU threads (invocations) that run on one compute unit and can share fast on-chip memory and synchronise.' },
  roofline: { term: 'Roofline model', def: 'Performance ≤ min(peak FLOP/s, bandwidth × arithmetic intensity). Arithmetic intensity = FLOPs per byte moved.' },
  mms: { term: 'Manufactured solution', def: 'A chosen exact solution $u$ from which the right-hand side $f$ and boundary data are computed, so that the error of a code can be measured exactly.' },
};
