/**
 * @file List of all test files (the browser cannot list directories).
 * Keep sorted; tests/unit/manifest.test.js checks it against the file system.
 */
export const TEST_FILES = [
  'conv/advbc1d.test.js',
  'conv/cg.test.js',
  'conv/dd.test.js',
  'conv/dg1d.test.js',
  'conv/dg2d.test.js',
  'conv/euler.test.js',
  'conv/fr1d.test.js',
  'conv/fv1d-hires.test.js',
  'conv/fv1d.test.js',
  'conv/fv2d.test.js',
  'conv/gpu-dgadv.test.js',
  'conv/immersed.test.js',
  'conv/poisson1d.test.js',
  'conv/webspline.test.js',
  'gpu/dgadv-gpu.test.js',
  'unit/basis.test.js',
  'unit/cutquad.test.js',
  'unit/dd.test.js',
  'unit/dgref.test.js',
  'unit/dgspectrum.test.js',
  'unit/frcorrections.test.js',
  'unit/gpu-cputwin.test.js',
  'unit/gpu-model.test.js',
  'unit/interp.test.js',
  'unit/la.test.js',
  'unit/manifest.test.js',
  'unit/mesh.test.js',
  'unit/quad.test.js',
  'unit/rk.test.js',
];
